# Generated by Django 5.0.1 on 2024-07-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
